# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b7f1ac4f3b9cd7fba54bf94a36db023e80cf36d3bd526589e95090e148028c81335b6cd5c8bd6e9f2f78bb02cacf58156dbcc98021fe894e2e922851dc69277

test:
  secret_key_base: e5ecb9d090990c9819bae234e60dd61453adfd2d838fc7d60aa97b5c8edf948543daaa8180468e324af7c82a3c9eb637d85689c96bfd0f778d9d13d644e95b92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
